DROP TABLE IF EXISTS users cascade;
DROP TABLE IF EXISTS  profiles cascade ;

CREATE TABLE profiles  (
    ID INT PRIMARY KEY AUTO_INCREMENT ,
    LABEL VARCHAR(500),
    CREATED DATE DEFAULT NULL ,
    STATUS VARCHAR(50)
);


CREATE TABLE users  (
    ID INT PRIMARY KEY AUTO_INCREMENT ,
    USERNAME VARCHAR(50) DEFAULT NULL ,
    LOGIN VARCHAR(50) ,
    PASSWORD VARCHAR(50) ,
    TOKEN VARCHAR(100) ,
    PROFIL_ID INT DEFAULT NULL ,
    STATUS VARCHAR(50) ,
    CREATED DATE DEFAULT NULL ,
    FOREIGN KEY (PROFIL_ID) REFERENCES profiles(ID) ON  DELETE CASCADE
);


INSERT INTO profiles (LABEL , CREATED) VALUES ('ADMIN',NOW()) ;
INSERT INTO profiles (LABEL , CREATED) VALUES ('EMPLOYER',NOW()) ;

INSERT INTO users (USERNAME ,LOGIN , PASSWORD , TOKEN , PROFIL_ID) VALUES('JON DOH','ADMIN','00000',NULL ,1);
INSERT INTO users (USERNAME ,LOGIN , PASSWORD , TOKEN , PROFIL_ID) VALUES('SERGE DOH','EMPLOYER','00000',NULL ,2);




